name: Build and Deploy Docker image

on:
  push:
    branches:
    - master
    - clair

env:
  AWS_REGION: us-east-1

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: use klar
      run: |
        wget -q https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64 -O klar
        chmod +x klar
        CLAIR_OUTPUT=High CLAIR_ADDR=http://clair.3r1.co:6060 ./klar 3r1co/juice-shop:sha-$(git rev-parse --short HEAD)