name: Build and Deploy Docker image

on:
  push:
    branches:
    - master
    - clair

env:
  AWS_REGION: us-east-1

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: |
        npm install --production --unsafe-perm
    - name: use klar
      run: |
        go get github.com/optiopay/klar
        CLAIR_ADDR=http://clair.3r1.co:6060 klar postgres:9.5.1